nlesc-nano/CAT

CAT/analysis/ligand_bde.py, CAT/data_handling/input_sanitizer.py, docs/5_bde.rst
Implemented the option to perform a XYn search based on core atoms (X) rather than ligands (Y)
=> Implemented https://github.com/nlesc-nano/CAT/issues/27

CAT/data_handling/mol_import.py
Cycle through previously visited atom IDs when all valid combinations are exhausted.
=> Bug fix: Increase the maximum number of .pdf atom ID's

CAT/attachment/qd_opt_ff.py
* Fixed an issue where the moleculair charged was not properly set to zero during the creation of .psf files.
=> Fixed an issue where the moleculair charged was not properly set to zero

CAT/data_handling/validate_ff.py
* Ensure the ``"use_ff"`` key updates previously existing Settings rather than completely overwriting them.
=> Ensure the ``"use_ff"`` updates settings rather than overwriting them

docs/12_4_recipes.rst, docs/12_recipes.rst
See https://github.com/nlesc-nano/nano-CAT/issues/43.
=> Added a new recipe to the documentation

docs/12_9_recipes.rst, docs/12_recipes.rst
See https://github.com/nlesc-nano/nano-CAT/pull/52.
=> Update documentation for Nano-CAT 0.5.3

CAT/attachment/ligand_opt.py, CAT/jobs.py
* Add additional checks for checking job statuses.
=> Add additional checks for checking job statuses

CAT/utils.py, CAT/workflows/workflow.py, CAT/workflows/workflow_dicts.py, docs/conf.py, setup.py
* Cleaned up the annotations in `CAT.workflows`.
* Be more strict about the required Sphinx version.
=> Maintenance and Sphinx version update

CAT/__version__.py, CAT/workflows/workflow.py, CHANGELOG.rst, README.rst, docs/7_database.rst, docs/conf.py, setup.py
*  Update the documentation for https://github.com/nlesc-nano/data-CAT/pull/25.
=> Documentation update

.environment.yaml, .readthedocs.yml, docs/0_documentation.rst, docs/14_pdb_container.rst, docs/15_dtype.rst, docs/16_hdf5_logging.rst, docs/conf.py
See https://github.com/nlesc-nano/data-CAT/pull/32.
=> Update the Data-CAT documentation

docs/14_pdb_container.rst
See https://github.com/nlesc-nano/data-CAT/pull/33.
=> data-CAT documentation update

setup.py
Try to use a newer version of pandas
=> change pandas version to >= 1.0.0

CAT/dye/addlig.py
* Cleaned up the `_load_sa_model()` and `sa_scores()` functions.
* Made the `filename` parameter in `sa_scores()` optional.
=> Cleaned up `_load_sa_model()` and `sa_scores()`

CAT/attachment/ligand_attach.py, CAT/attachment/ligand_opt.py, CAT/attachment/mol_split_cm.py, CAT/workflows/workflow.py, CAT/workflows/workflow_dicts.py, examples/input.py
Closes https://github.com/nlesc-nano/CAT/issues/153 in conjunction with https://github.com/nlesc-nano/data-CAT/pull/45.
=> BUG: Fix an issue where indices weren't properly passed to the database

CAT/data_handling/validate_input.py
=> Improve the code-style of validating input

CAT/data_handling/validate_input.py, tests/test_files/input1.yaml, tests/test_validate_input.py
Closes https://github.com/nlesc-nano/CAT/issues/166.
~~Pink~~ Ping @felipeZ
=> Fixed an issue where the core anchor is not properly parsed

CAT/__init__.py, CAT/base.py, CAT/data_handling/mol_import.py, CAT/data_handling/validate_input.py, CAT/data_handling/validate_mol.py, CAT/data_handling/validation_schemas.py, tests/test_validate_input.py, tests/test_validate_mol.py
=>  ENH: Ensure that CAT settings can be validated multiply times without raising exceptions

CAT/base.py, CAT/data_handling/validate_input.py, CAT/data_handling/validate_mol.py, CAT/data_handling/validation_schemas.py, CAT/utils.py, setup.py, tests/test_validate_input.py
=> ENH: Added the `validate_only` keyword to `validate_input()`

docs/12_10_recipes.rst, docs/12_recipes.rst, setup.py
xref https://github.com/nlesc-nano/nano-CAT/pull/67.
=> DOC: Added documentation for the new entropy recipe

CAT/workflows/workflow.py, setup.py
With the merging of https://github.com/SCM-NV/PLAMS/pull/87 the previous `Settings`-related issue has been resolved and 
we no longer have to pin a specific PLAMS version.
=> MAINT: Relax the PLAMS version

.github/workflows/pythonpackage.yml, CAT/attachment/ligand_anchoring.py, CAT/attachment/mol_split_cm.py, CAT/data_handling/validate_input.py, README.rst, examples/input_settings.yaml, setup.py, tests/test_entry_points.py, tests/test_sphinx.py, tests/test_validate_input.py
ping @ultimoboulevard.
RDKit functions can return `None`, instead of raising, under rare circumstances, which can cause issues down the line.
This PR fixes aforementioned issue which was encountered in the CAT `substructure_split` function.
=> BUG: Fixed an issue wherein `substructure_split` could fail 

CAT/gen_job_manager.py
Check that the to-be loaded directory exists before marking a job as loaded.
=> BUG: Fixed an issue wherein loading previous jobs could fail

.github/workflows/pypi.yaml, CAT/__version__.py, CHANGELOG.rst, MANIFEST.in, README.rst, docs/conf.py, setup.cfg, setup.py
* Add more advanced anchor-parsing options.
* Update for AMS 2021.
* Fixed various issues.
=> REL: Release CAT 0.10.0

CAT/data_handling/validation_schemas.py, CAT/workflows/workflow.py, CAT/workflows/workflow_yaml.yaml, docs/5_bde.rst, tests/test_schemas.py
Enables or disables an (AMS-based) preoptimization of the XYn fragment at the UFF level of theory.
=> ENH: Expose a keyword for the BDE XYn-preoptimization

CAT/data_handling/validation_schemas.py
Xref https://github.com/nlesc-nano/nano-CAT/pull/118
=> ENH: Add the `remove_anchor_hydrogens` option to the cone-angle workflow

CAT/logger.py
Fixes a regression introduced in https://github.com/nlesc-nano/CAT/pull/207.
=> BUG: Fix the CAT logger failing to write to stdout

CAT/data_handling/mol_import.py, tests/test_mol_import.py
=> ENH: Set the default Indium (formal) charge to 3+

.github/workflows/pypi.yaml, .github/workflows/pythonpackage.yml, CAT/__version__.py, CHANGELOG.rst, README.rst, setup.py
Bump CAT to 1.0.0 in anticipiation of the new *J. Chem. Inf. Model.* paper.
=> REL: Bump CAT to 1.0.0
