nlesc-nano/CAT

CAT/base.py, CAT/data_handling/validation_schemas.py, tests/test_schemas.py
In other words: ``Schema.And()`` was replaced with ``Schema.Or()``.
=> Bug fix: the subset Schema now checks for instances of int Or float

CAT/attachment/distribution.py, examples/input.py, tests/test_distribution.py
* Fixed a bug where ``uniform_idx()`` yielded the rolled, rather than unshifted, indices.
=> ``uniform_idx()`` now returns the correct indices

CAT/data_handling/validation_schemas.py, docs/11_md_asa.rst
* Added the "distance_upper_bound" and "k" keywords for the MD-ASA procedure (see https://github.com/nlesc-nano/nano-CAT/pull/28).
=> Added the "distance_upper_bound" and "k" keywords for the MD-ASA procedure

CAT/attachment/ligand_attach.py, CAT/data_handling/__init__.py, CAT/data_handling/str_to_func.py, CAT/data_handling/warn_map.py, CAT/mol_utils.py, tests/test_mol_utils.py
* Issue a warning when ligand atoms are too close (<1 Angstrom) when constructing quantum dots.
* Improved warning handling.
* Removed a number of redundant functions.
=> Issue a warning when ligand atoms are too close when constructing QDs

CAT/attachment/ligand_attach.py, CAT/data_handling/warn_map.py, CAT/workflows/workflow_dicts.py
* Fixed an issue where an incorrect offset was within ``_evaluate_distance()``
* Improved warning handling.
=>  Fixed an issue where an incorrect offset was within _evaluate_distance()

CAT/attachment/ligand_attach.py
* Ensure that part of the core-surface is accounted for when rotating ligands.
=> Ensure that part of the core-surface is accounted for when rotating ligands

CAT/jobs.py
* ``Job.hash()`` will return ``None`` if rerun prevention is disabled; ``f.write(None)`` consequently raising a ``TypeError``.
=> Added a try/except clause for job hashing in case rerun prevention is disabled

.github/workflows/pythonpackage.yml, CAT/recipes.py, CHANGELOG.rst, setup.py, tests/test_CAT.py, tests/test_sphinx.py
Implementation of https://github.com/nlesc-nano/CAT/issues/125:
* Re-enabled tests for Python 3.6.
=> Re-enable Python 3.6 tests

CAT/attachment/ligand_opt.py, CAT/base.py, CHANGELOG.rst
* Only perform `optional.ligand.optimize.job2` if the preceding UFF optimization finishes without crashing.
* Remove a ligand if its optimization fails (_i.e._ an exception is raised).
=> Skip the second stage optimization if the first one fails

CAT/__version__.py, CHANGELOG.rst, README.rst, docs/conf.py
Closes https://github.com/nlesc-nano/CAT/issues/143.
=> Version bump: 0.9.6 > 0.9.7

CAT/__version__.py, CAT/data_handling/validation_schemas.py, CAT/utils.py, CAT/workflows/workflow.py, CAT/workflows/workflow_yaml.yaml, README.rst, docs/1_get_started.rst, docs/4_optional.rst, docs/conf.py, tests/test_files/input4.yaml, tests/test_schemas.py, tests/test_thread_safe.py, tests/test_validate_input.py
Closes https://github.com/nlesc-nano/CAT/issues/149.
This pull request adds the `optional.database.thread_safe` keyword, which can be set to `True` to create PLAMS workdirs with thread-safe names.
=> ENH: Added to option to create workdirs with thread-safe names

CAT/__init__.py
For some reason the `matplotlib` logger is going bananas.
Change its level from `DEBUG` (default) to `INFO` in order to silence it.
=> Forcefully set the matplotlib logging level to `INFO`

.environment.yaml, .readthedocs.yml, setup.py
<details>
```
Read the Docs build information
Build id: 12198155
Project: cat
Version: latest
Commit: 3b8523f78ba179f3260d51b43bc066f3eef70d90
Date: 2020-10-27T13:15:51.255311Z
State: finished
Success: False
[rtd-command-info] start-time: 2020-10-27T13:15:55.244296Z, end-time: 2020-10-27T13:15:58.040923Z, duration: 2, exit-code: 0
git clone --no-single-branch --depth 50 https://github.com/nlesc-nano/CAT.git .
Cloning into '.'...
[rtd-command-info] start-time: 2020-10-27T13:15:58.498907Z, end-time: 2020-10-27T13:15:58.621371Z, duration: 0, exit-code: 0
git checkout --force origin/master
Note: checking out 'origin/master'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting …
```
=> DOC: Fix the readthedocs failure

CAT/attachment/ligand_anchoring.py, CAT/base.py, CAT/data_handling/validate_input.py, CAT/data_handling/validation_schemas.py, CAT/multi_ligand.py, CAT/workflows/workflow_yaml.yaml, docs/13_multi_ligand.rst, docs/1_get_started.rst, docs/4_optional.rst, tests/test_files/CAT.yaml, tests/test_files/CAT_indices.yaml, tests/test_files/input2.yaml, tests/test_files/input3.yaml, tests/test_files/input4.yaml, tests/test_schemas.py, tests/test_validate_input.py
Closes https://github.com/nlesc-nano/CAT/issues/163.
Adds the new `optional.core.anchor` and `optional.ligand.functional_groups` options,
which are respectively aliases for the old `optional.core.dummy` and `optional.ligand.functional_groups` options.
=> Make `dummy` and `functional_groups` aliases for `anchor`

CAT/data_handling/validate_input.py, CAT/data_handling/validation_schemas.py, CAT/workflows/workflow_yaml.yaml, docs/4_optional.rst
Adds two new bulkiness-related options:
``` yaml
optional:
qd:
bulkiness:
h_lim: 10.0
d: "auto"
```
Dependent on https://github.com/nlesc-nano/nano-CAT/pull/69.
=> ENH: Added the new `bulkiness.h_lim` and `bulkiness.d` options

CAT/gen_job_manager.py
This can cause issue with certain parallel-distribution systems, 
the absolute path referring to the login node rather than the compute nodes.
Ping @felipeZ
=> MAINT: Do not call `os.path.abspath()` when loading jobs

.environment.yaml, .github/workflows/pythonpackage.yml
Pip 20.3 has issues with handling the CAT/data-CAT dependency chain:
from https://github.com/nlesc-nano/CAT/runs/1588660340?check_suite_focus=true:
```
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The conflict is caused by:
cat[test] 0.9.11 depends on cat 0.9.11 (from /home/runner/work/CAT/CAT)
data-cat 0.5.2 depends on cat 0.9.11 (from git+https://github.com/nlesc-nano/CAT)
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
=> TST: Freeze the pip version

CAT/__init__.py, CAT/attachment/distribution.py, CAT/distribution.py, docs/0_documentation.rst, docs/18_distribution.rst, docs/_3_distribution.rst
Exposed via the new `CAT.distribution` module.
=>  ENH: Expose the `distribution` module to the main CAT namespace 

.github/workflows/pythonpackage.yml, CAT/base.py, docs/4_optional.rst, setup.py, tests/test_CAT.py
The user should either provide more anchor atoms (>= 4) or switch to `optional.core.allignment = "sphere"`.
=> MAINT: Raise a `NotImplementedError` if a core has an insufficient number of anchors

CAT/attachment/ligand_attach.py
If the passed array is smaller than the range spanned by `k` (_i.e._ if the core is very small) 
then the indices returned by `cKDTree` are padded. Remove the padding before continuing, 
preventing any further `IndexError`s.
=> BUG: Fixed an issue wherein small cores would fail with the `cKDTree`

.github/workflows/pythonpackage.yml
It appears `scipy` and `h5py` MacOS wheels are missing for Python 3.9 and building them from source has failed thus far.
Install both packages via conda.
=> TST: Fix the macos python 3.9 CI failure

CAT/attachment/ligand_anchoring.py, CAT/data_handling/mol_import.py, CAT/multi_ligand.py, CAT/utils.py, setup.py, tests/test_gen_job_manager.py, tests/test_mol_import.py, tests/test_utils.py
Xref https://github.com/nlesc-nano/CAT/pull/209
Backport in preparation for the changes introduced in https://github.com/SCM-NV/PLAMS/commit/610083639eb6ca9826daee1ef52eb96d22c38480, 
which switches Hill-system-based formula notation rather than the previous purelly alphabetical notation.
=> MAINT: Backport the PLAMS <= 1.5.1 `Molecule.get_formula` method

.github/workflows/pythonpackage.yml, CHANGELOG.rst
=> TST: Add a dedicated CI job for pre-releases

.github/workflows/pythonpackage.yml, CAT/_mol_str_parser.py, CAT/attachment/ligand_anchoring.py, CAT/data_handling/anchor_parsing.py, CAT/multi_ligand.py, CAT/utils.py, docs/4_optional.rst, tests/test_ligand_anchoring.py, tests/test_ligand_attach.py, tests/test_mol_str_parser.py, tests/test_utils.py
Adds the new `anchor.group_format` option, which can be used for specifying the format used for `anchor.group` (*e.g.* SMILES or SMARTS).
Examples
---------
``` yaml
optional:
ligand:
anchor:
group: "[H]-[#8]"  # i.e. "[H]O"
group_idx: 1
group_format: "SMARTS"
```
=> ENH: Allow specifying the format type of the anchor `group`

CAT/_mol_str_parser.py
The underlying `MolFromPNGString` and `MolFromPNGFile` functions are unavailable in prior versions.
=> BUG: Disable the `PNG` and `PNG_FILE` anchor format options for RDKit <2020.09.01

CAT/data_handling/anchor_parsing.py, CAT/mol_utils.py, tests/test_ligand_anchoring.py
Manually construct the reference group-molecules if mono-atomic anchors are encountered that lack RDKit SMILES support, _e.g._ `anchor.group: "Rb"`.
=> BUG: Fix an issue wherein anchor-group-parsing could fail for mono-atomic anchors

.github/workflows/pythonpackage.yml, README.rst, setup.py
Automatically use install `rdkit` via [pypi](https://pypi.org/project/rdkit-pypi/) when it's not pre-installed via conda.
=> BLD: Allow installing `CAT` without the use of conda

CAT/data_handling/validate_input.py, CAT/data_handling/validation_schemas.py
It should be possible to specify either the BDE `core_atom` or `lig_count` options, while previously the `core_atom` was (incorrectly) considered mandatory.
=> BUG: Fix the BDE `core_atom` and `lig_count` keys not being optional

CAT/data_handling/validation_schemas.py, CAT/workflows/workflow_yaml.yaml, CHANGELOG.rst, docs/5_bde.rst, tests/test_schemas.py
Adds ``qd.dissociate.qd_opt`` keyword, which is used for optimizing the QD and XYn-dissociated QD in the dissociation workflow.
=> ENH: Add the ``qd.dissociate.qd_opt`` keyword

CAT/data_handling/validation_schemas.py, docs/4_optional.rst
Part of https://github.com/nlesc-nano/nano-CAT/issues/115.
Allows the `optional.qd.bulkiness.d` option to take both floats as well as list of floats, the latter computing the bulkiness for a range of different lattice spacing values.
=> ENH: Allow multiple values for the bulkiness latice spacing

CAT/attachment/core_anchoring.py, CAT/attachment/ligand_anchoring.py, CAT/attachment/ligand_attach.py, CAT/data_handling/mol_import.py, tests/test_mol_import.py, tests/test_multi_ligand.py
cc @juliette1996 
The `anchor.kind = "mean"` keyword would previously put the ligand in the correct translation and rotation, but would fail to use this information when actually combining the core and ligands into a single quantum dot.
Examples
----------
An example of a superimposed core and it's QD, both carboxyl oxygens being used as `mean` anchor:
=> BUG: Fix the `anchor.kind = "mean"` keyword being broken

CAT/data_handling/mol_import.py, CAT/data_handling/validate_mol.py, CAT/data_handling/validation_schemas.py, docs/3_input_core_ligand.rst, tests/test_mol_import.py, tests/test_schemas.py, tests/test_validate_mol.py
Closes https://github.com/nlesc-nano/CAT/issues/262
Adds the option to explicitly enable or disable the canonicalization of input molecules.
Examples
----------
``` yaml
input_cores:
- Cd68Se55.xyz
input_ligands:
- OC(C)=O:
canonicalize: True
- OC(CC)=O:
canonicalize: False
```
=> ENH: Add the option to disable ligand canonicalization

.readthedocs.yml, CAT/utils.py
CC @RobertaPascazio 
Get rid of `pkg_resources` due to a number of deprecations and recent issues with running it on one of the clusters.
=> MAINT: Get rid `pkg_resources`
